#include "server.h"

// Note: do NOT define CPPHTTPLIB_OPENSSL_SUPPORT / ZLIB / BROTLI at all —
// cpp-httplib uses #ifdef which is true for any defined value (even 0).
#include <httplib.h>

#include <chrono>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <utility>

#include <sys/stat.h>

#include <nlohmann/json.hpp>

#include "log.h"
#include "metrics.h"
#include "ofiq_runner.h"

#include "index_html.h"   // generated by CMake from web/index.html

namespace ofiq_api {

namespace {

constexpr const char* kServerVersion = "0.1.0";
constexpr const char* kOfiqVersion   = "1.1.2";

std::string make_request_id(std::uint64_t n) {
    char buf[32];
    std::snprintf(buf, sizeof(buf), "r-%012llx", static_cast<unsigned long long>(n));
    return buf;
}

void cors_headers(httplib::Response& res) {
    res.set_header("Access-Control-Allow-Origin", "*");
    res.set_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
    res.set_header("Access-Control-Allow-Headers", "Content-Type, Accept");
}

void respond_json(httplib::Response& res, int status, const nlohmann::json& body) {
    res.status = status;
    res.set_content(body.dump(), "application/json; charset=utf-8");
}

void respond_text(httplib::Response& res, int status, std::string text, const char* ctype) {
    res.status = status;
    res.set_content(std::move(text), ctype);
}

} // namespace

struct Server::Impl {
    httplib::Server svr;
};

Server::Server(ServerConfig srv_cfg, WorkerPoolConfig wp_cfg, VerdictPolicy policy)
    : cfg_(std::move(srv_cfg)),
      policy_(std::move(policy)),
      pool_(std::make_unique<WorkerPool>(std::move(wp_cfg))),
      impl_(std::make_unique<Impl>()) {

    Metrics::instance().set_workers_total(pool_->workers_total());
    Metrics::instance().set_queue_depth(pool_->queue_depth());

    auto& svr = impl_->svr;

    svr.set_payload_max_length(cfg_.max_upload_bytes + 64 * 1024);
    svr.set_read_timeout(cfg_.request_timeout);
    svr.set_write_timeout(cfg_.request_timeout);
    svr.set_keep_alive_max_count(cfg_.keep_alive_max_count);
    svr.set_keep_alive_timeout(5);

    svr.set_error_handler([](const httplib::Request&, httplib::Response& res) {
        if (res.body.empty()) {
            nlohmann::json j = {{"error", "internal"}, {"status", res.status}};
            res.set_content(j.dump(), "application/json");
        }
        Metrics::instance().inc_requests_total(res.status);
    });

    svr.set_exception_handler([](const httplib::Request&, httplib::Response& res, std::exception_ptr ep) {
        std::string what;
        try { if (ep) std::rethrow_exception(ep); }
        catch (const std::exception& e) { what = e.what(); }
        catch (...)                     { what = "unknown"; }
        log::error("unhandled exception in handler",
                   std::string(R"("error":")") + log::escape(what) + R"(")");
        nlohmann::json j = {{"error", "internal_exception"}, {"detail", what}};
        res.status = 500;
        res.set_content(j.dump(), "application/json");
    });

    svr.set_pre_routing_handler([](const httplib::Request& req, httplib::Response& res) {
        cors_headers(res);
        if (req.method == "OPTIONS") {
            res.status = 204;
            return httplib::Server::HandlerResponse::Handled;
        }
        return httplib::Server::HandlerResponse::Unhandled;
    });

    // ---- root: HTML upload page ---------------------------------------
    svr.Get("/", [this](const httplib::Request&, httplib::Response& res) {
        std::string html;
        if (!cfg_.index_html_path.empty()) {
            struct stat st{};
            if (::stat(cfg_.index_html_path.c_str(), &st) == 0 && S_ISREG(st.st_mode)) {
                std::ifstream f(cfg_.index_html_path, std::ios::binary);
                if (f.is_open()) {
                    std::ostringstream os;
                    os << f.rdbuf();
                    html = os.str();
                }
            }
            if (html.empty()) {
                log::warn("index_html_path unreadable, falling back to embedded",
                          std::string(R"("path":")") + log::escape(cfg_.index_html_path) + R"(")");
            }
        }
        if (html.empty()) {
            html.assign(reinterpret_cast<const char*>(kIndexHtml), kIndexHtmlLen);
        }
        respond_text(res, 200, std::move(html), "text/html; charset=utf-8");
        Metrics::instance().inc_requests_total(200);
    });

    svr.Get("/healthz", [](const httplib::Request&, httplib::Response& res) {
        respond_text(res, 200, "ok\n", "text/plain");
        Metrics::instance().inc_requests_total(200);
    });

    svr.Get("/readyz", [this](const httplib::Request&, httplib::Response& res) {
        if (pool_->ready()) {
            respond_text(res, 200, "ready\n", "text/plain");
            Metrics::instance().inc_requests_total(200);
        } else {
            respond_text(res, 503, "not ready\n", "text/plain");
            Metrics::instance().inc_requests_total(503);
        }
    });

    svr.Get("/version", [](const httplib::Request&, httplib::Response& res) {
        nlohmann::json j = {
            {"server", kServerVersion},
            {"ofiq",   kOfiqVersion}
        };
        respond_json(res, 200, j);
        Metrics::instance().inc_requests_total(200);
    });

    svr.Get("/metrics", [this](const httplib::Request&, httplib::Response& res) {
        Metrics::instance().set_workers_busy(pool_->workers_busy());
        Metrics::instance().set_workers_ready(pool_->workers_ready());
        Metrics::instance().set_queue_size(pool_->queue_size());
        respond_text(res, 200,
                     Metrics::instance().render_prometheus(),
                     "text/plain; version=0.0.4");
        Metrics::instance().inc_requests_total(200);
    });

    svr.Post("/v1/validate", [this](const httplib::Request& req, httplib::Response& res) {
        const auto t0 = std::chrono::steady_clock::now();
        const std::string rid = make_request_id(next_request_id_.fetch_add(1));

        auto log_request = [&](int status, double elapsed_ms, std::string_view extra) {
            std::ostringstream os;
            os << R"("rid":")" << rid << R"(","status":)" << status
               << R"(,"ms":)" << elapsed_ms;
            if (!extra.empty()) os << ',' << extra;
            log::info("request", os.str());
        };

        if (!pool_->ready()) {
            res.set_header("Retry-After", "5");
            nlohmann::json j = {{"error", "not_ready"}};
            respond_json(res, 503, j);
            Metrics::instance().inc_requests_total(503);
            log_request(503, 0, R"("reason":"not_ready")");
            return;
        }

        if (!req.has_file("file")) {
            nlohmann::json j = {{"error", "missing_file_field"},
                                {"hint",  "POST multipart/form-data with field 'file'"}};
            respond_json(res, 400, j);
            Metrics::instance().inc_requests_total(400);
            log_request(400, 0, R"("reason":"missing_file")");
            return;
        }

        const auto& upload = req.get_file_value("file");
        if (upload.content.size() > cfg_.max_upload_bytes) {
            nlohmann::json j = {{"error", "payload_too_large"},
                                {"max_bytes", cfg_.max_upload_bytes},
                                {"got_bytes", upload.content.size()}};
            respond_json(res, 413, j);
            Metrics::instance().inc_requests_total(413);
            log_request(413, 0, R"("reason":"too_large")");
            return;
        }

        DecodeError derr;
        DecodedImage dec = decode_image(upload.content.data(), upload.content.size(), derr);
        if (!dec.ok()) {
            Metrics::instance().inc_decode_failed();
            nlohmann::json j = {{"error", "decode_failed"}, {"detail", derr.message}};
            respond_json(res, 415, j);
            Metrics::instance().inc_requests_total(415);
            log_request(415, 0, R"("reason":"decode_failed")");
            return;
        }

        auto h = pool_->submit(dec.image, rid);
        if (!h.has_value()) {
            Metrics::instance().inc_queue_full();
            res.set_header("Retry-After", "1");
            nlohmann::json j = {{"error", "queue_full"}};
            respond_json(res, 503, j);
            Metrics::instance().inc_requests_total(503);
            log_request(503, 0, R"("reason":"queue_full")");
            return;
        }

        const auto t_inf_start = std::chrono::steady_clock::now();
        if (h->result.wait_for(cfg_.request_timeout) != std::future_status::ready) {
            nlohmann::json j = {{"error", "timeout"}};
            respond_json(res, 504, j);
            Metrics::instance().inc_requests_total(504);
            log_request(504, 0, R"("reason":"timeout")");
            return;
        }
        OFIQ::FaceImageQualityAssessment assessment;
        std::string werr;
        try {
            assessment = h->result.get();
            werr = h->error.get();
        } catch (const std::exception& e) {
            werr = e.what();
        }
        const auto t_inf_end = std::chrono::steady_clock::now();
        const double inf_ms = std::chrono::duration<double, std::milli>(t_inf_end - t_inf_start).count();
        Metrics::instance().observe_inference_duration_ms(inf_ms);

        if (!werr.empty()) {
            nlohmann::json j = {{"error", "inference_failed"}, {"detail", werr}};
            respond_json(res, 500, j);
            Metrics::instance().inc_requests_total(500);
            log_request(500, inf_ms,
                        std::string(R"("reason":"inference_failed","detail":")")
                        + log::escape(werr) + R"(")");
            return;
        }

        nlohmann::json out = ofiq_api::assessment_to_json(assessment);
        out["request_id"]   = rid;
        out["server"]       = kServerVersion;
        out["ofiq_version"] = kOfiqVersion;
        out["image"] = {
            {"width",        dec.orig_width},
            {"height",       dec.orig_height},
            {"channels",     dec.orig_channels},
            {"upload_bytes", upload.content.size()}
        };
        const auto t1 = std::chrono::steady_clock::now();
        const double total_ms = std::chrono::duration<double, std::milli>(t1 - t0).count();
        out["elapsed_ms"]   = total_ms;
        out["inference_ms"] = inf_ms;
        out["verdict"] = policy_.evaluate(assessment);

        respond_json(res, 200, out);
        Metrics::instance().inc_requests_total(200);
        Metrics::instance().observe_request_duration_ms(total_ms);

        std::ostringstream extra;
        extra << R"("inf_ms":)" << inf_ms
              << R"(,"compliant":)" << (out["verdict"]["icao_compliant"].get<bool>() ? "true" : "false");
        log_request(200, total_ms, extra.str());
    });
}

Server::~Server() { stop(); }

bool Server::start() {
    log::info("waiting for workers to initialize");
    if (!pool_->wait_until_ready(cfg_.startup_timeout)) {
        log::error("no workers became ready");
        return false;
    }
    Metrics::instance().set_workers_ready(pool_->workers_ready());

    std::ostringstream os;
    os << R"("host":")" << cfg_.host << R"(","port":)" << cfg_.port
       << R"(,"workers":)" << pool_->workers_ready() << '/' << pool_->workers_total();
    log::info("server listening", os.str());

    return impl_->svr.listen(cfg_.host, cfg_.port);
}

void Server::stop() {
    if (impl_) {
        impl_->svr.stop();
    }
    if (pool_) {
        pool_->shutdown();
    }
}

} // namespace ofiq_api
